### ISSUE TITLE
Please create a dummy version/tag

### ISSUE THREAD

**Issue by hhoffstaette** [ponycloud/python-sysfs#5]
Hi! I'm trying to package this nice little library for Gentoo. I could get by with just using a datestamp
for the package version, but a proper release tag would make this much easier.
A simple "1.0" tag/release of the current master branch would do.

**Comment by koudi** [comment]
Hi, is this ok?

https://github.com/ponycloud/python-sysfs/releases/tag/v1.0

**Comment by hhoffstaette** [comment]
Perfect - Thank you!
